### Audio
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/config/audio/mixer_paths_tasha.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_tasha.xml \
    $(DEVICE_PATH)/config/audio/audio_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info.xml

### Modem Configs
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/config/modem/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/modem.conf \
    $(DEVICE_PATH)/config/modem/2/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/2/modem.conf \
    $(DEVICE_PATH)/config/modem/3/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/3/modem.conf \
    $(DEVICE_PATH)/config/modem/13/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/13/modem.conf \
    $(DEVICE_PATH)/config/modem/34/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/34/modem.conf \
    $(DEVICE_PATH)/config/modem/37/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/37/modem.conf \
    $(DEVICE_PATH)/config/modem/38/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/38/modem.conf \
    $(DEVICE_PATH)/config/modem/39/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/39/modem.conf \
    $(DEVICE_PATH)/config/modem/40/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/40/modem.conf \
    $(DEVICE_PATH)/config/modem/41/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/41/modem.conf \
    $(DEVICE_PATH)/config/modem/42/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/42/modem.conf \
    $(DEVICE_PATH)/config/modem/54/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/54/modem.conf \
    $(DEVICE_PATH)/config/modem/55/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/55/modem.conf \
    $(DEVICE_PATH)/config/modem/57/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/57/modem.conf \
    $(DEVICE_PATH)/config/modem/58/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/58/modem.conf \
    $(DEVICE_PATH)/config/modem/59/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/59/modem.conf \
    $(DEVICE_PATH)/config/modem/62/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/62/modem.conf \
    $(DEVICE_PATH)/config/modem/71/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/71/modem.conf \
    $(DEVICE_PATH)/config/modem/73/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/73/modem.conf \
    $(DEVICE_PATH)/config/modem/79/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/79/modem.conf \
    $(DEVICE_PATH)/config/modem/88/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/88/modem.conf \
    $(DEVICE_PATH)/config/modem/92/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/92/modem.conf \
    $(DEVICE_PATH)/config/modem/93/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/93/modem.conf \
    $(DEVICE_PATH)/config/modem/94/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/94/modem.conf \
    $(DEVICE_PATH)/config/modem/114/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/114/modem.conf \
    $(DEVICE_PATH)/config/modem/122/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/122/modem.conf \
    $(DEVICE_PATH)/config/modem/132/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/132/modem.conf \
    $(DEVICE_PATH)/config/modem/133/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/133/modem.conf \
    $(DEVICE_PATH)/config/modem/134/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/134/modem.conf \
    $(DEVICE_PATH)/config/modem/170/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/170/modem.conf \
    $(DEVICE_PATH)/config/modem/177/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/177/modem.conf \
    $(DEVICE_PATH)/config/modem/184/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/184/modem.conf \
    $(DEVICE_PATH)/config/modem/191/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/191/modem.conf \
    $(DEVICE_PATH)/config/modem/192/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/192/modem.conf \
    $(DEVICE_PATH)/config/modem/193/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/193/modem.conf \
    $(DEVICE_PATH)/config/modem/196/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/196/modem.conf \
    $(DEVICE_PATH)/config/modem/198/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/198/modem.conf \
    $(DEVICE_PATH)/config/modem/244/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/244/modem.conf \
    $(DEVICE_PATH)/config/modem/272/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/272/modem.conf \
    $(DEVICE_PATH)/config/modem/273/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/273/modem.conf \
    $(DEVICE_PATH)/config/modem/274/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/274/modem.conf \
    $(DEVICE_PATH)/config/modem/286/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/286/modem.conf \
    $(DEVICE_PATH)/config/modem/297/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/297/modem.conf \
    $(DEVICE_PATH)/config/modem/306/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/306/modem.conf \
    $(DEVICE_PATH)/config/modem/308/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/308/modem.conf \
    $(DEVICE_PATH)/config/modem/310/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/310/modem.conf \
    $(DEVICE_PATH)/config/modem/311/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/311/modem.conf \
    $(DEVICE_PATH)/config/modem/326/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/326/modem.conf \
    $(DEVICE_PATH)/config/modem/348/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/348/modem.conf \
    $(DEVICE_PATH)/config/modem/350/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/350/modem.conf \
    $(DEVICE_PATH)/config/modem/404/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/404/modem.conf \
    $(DEVICE_PATH)/config/modem/408/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/408/modem.conf \
    $(DEVICE_PATH)/config/modem/415/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/415/modem.conf \
    $(DEVICE_PATH)/config/modem/420/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/420/modem.conf \
    $(DEVICE_PATH)/config/modem/424/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/424/modem.conf \
    $(DEVICE_PATH)/config/modem/426/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/426/modem.conf \
    $(DEVICE_PATH)/config/modem/441/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/441/modem.conf \
    $(DEVICE_PATH)/config/modem/442/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/442/modem.conf \
    $(DEVICE_PATH)/config/modem/446/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/446/modem.conf \
    $(DEVICE_PATH)/config/modem/452/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/452/modem.conf \
    $(DEVICE_PATH)/config/modem/461/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/461/modem.conf \
    $(DEVICE_PATH)/config/modem/477/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/477/modem.conf \
    $(DEVICE_PATH)/config/modem/483/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/483/modem.conf \
    $(DEVICE_PATH)/config/modem/489/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/489/modem.conf \
    $(DEVICE_PATH)/config/modem/492/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/492/modem.conf \
    $(DEVICE_PATH)/config/modem/513/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/513/modem.conf \
    $(DEVICE_PATH)/config/modem/523/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/523/modem.conf \
    $(DEVICE_PATH)/config/modem/549/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/549/modem.conf \
    $(DEVICE_PATH)/config/modem/567/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/567/modem.conf \
    $(DEVICE_PATH)/config/modem/611/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/611/modem.conf \
    $(DEVICE_PATH)/config/modem/640/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/640/modem.conf
